### ISSUE TITLE
Text outline

### ISSUE THREAD

**Issue by escheelk** [mohamed-tayeh/Minimal-Pomo-Timer#31]
A nice feature would be having an text outline, for example black outline of variable size and white font color.  This would allow the text overlay to be readable and placed in many places in people's OBS scenes.

**Comment by mohamed-tayeh** [comment]
@escheelk that's a good suggestion i'll make sure it's implemented asap:)

**Comment by mohamed-tayeh** [comment]
![image](https://github.com/mohamed-tayeh/Minimal-Pomo-Timer/assets/35163331/88e41f34-4a7d-4507-ba16-984a8e0531e6)

**Comment by mohamed-tayeh** [comment]
I have implemented it, please excuse the delay.

I have added two properties outline size and outline color that allows you to customize it.

Eventually I will also be making the setup much easier and provide a user interface to edit these properties rather than setting them in code.

Will be closing the issue now, please feel free to re-open if there is an problem:)
